services:
  - type: web
    name: english-learn-bot
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install --upgrade --force-reinstall python-telegram-bot==20.7
    startCommand: python bot.py
